global:
  appName: ""
  namespace: ""
  enabledComponents:
    configmap: false
    service: true
    ingress: false
    secret: false

image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent
  pullSecret: ""

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  className: nginx
  hosts: []

configmap:
  data: {}
